### ISSUE TITLE
benchmarking

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/eiger-io#11]
If we're switching to dask, it would be useful to benchmark somewhere.

I would suggest starting with the 3D time series (ignore events, since anyway CHX usually deals with one event, with the exception of scanning):
```python
imgs # time series images PIMS object
roi1 = # some slice
t1 = time.time()
avgstat = 0
for img in imgs:
    avgstat += img[slice]
avgstat /= len(imgs)
t2 = time.time()
dt_pims =t2-t1

t1 = time.time()
imgs # dask array
avgstat = np.average(imgs[:, slice])
t2 = time.time()
dt_np = t2-t1
```

something like this
@danielballan what do you think?

**Comment by danielballan** [comment]
That looks sensible to me. I do suggest using a more sophisticated profiling tool (my go-to is the [`%timeit` magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit)) that takes some measures to avoid getting fooled by caching.
